# Telescope Configuration File
# Configuration for ROTSE-III Fork-Mounted Equatorial Mount

# Serial communication settings
serial:
  port: "/dev/ttyS0"          # Serial port device
  baudrate: 9600                # Communication speed  
  timeout: 3.0                  # Command timeout in seconds
  retries: 3                    # Number of retry attempts

# Telescope encoder limits (from initialization/homing)
limits:
  ha_positive: 3447618          # HA positive limit (home position after homing)
  dec_negative: -1560846        # Dec negative limit (home position after homing)
  # ha_negative and dec_positive are calculated automatically from ranges

# Encoder ranges (total travel distance)
ranges:
  ha_encoder_range: 4492409     # Total HA encoder travel
  dec_encoder_range: 4535993    # Total Dec encoder travel

# Coordinate system parameters
coordinates:
  observer_latitude: -23.2716   # Observer latitude in degrees (HESS site)
  dec_steps_per_degree: 19408.0 # Declination encoder steps per degree

# Motion parameters for different slew modes
motion:
  # Normal slewing (balanced speed and precision)
  normal:
    ha_velocity: 30000          # HA velocity in encoder steps/second
    dec_velocity: 15000         # Dec velocity (conservative for precision)
    ha_acceleration: 3000       # HA acceleration
    dec_acceleration: 1000      # Dec acceleration (very conservative)
  
  # Fast slewing (maximum speed)
  fast:
    ha_velocity: 50000
    dec_velocity: 25000
    ha_acceleration: 10000
    dec_acceleration: 5000
  
  # Precise slewing (slow and accurate)
  precise:
    ha_velocity: 5000
    dec_velocity: 3000
    ha_acceleration: 1000
    dec_acceleration: 300
  
  # Initialization moves (conservative post-homing)
  initialization:
    ha_velocity: 15000
    dec_velocity: 10000
    ha_acceleration: 2000
    dec_acceleration: 1000

# Tracking parameters
tracking:
  sidereal_rate_steps_per_sec: 104.0      # Sidereal tracking rate
  tracking_safety_margin_steps: 10000     # Stop tracking this many steps before limit

# Safety parameters
safety:
  slew_timeout_seconds: 300.0             # Maximum slew time
  position_tolerance_steps: 1000          # Position tolerance for slew completion
  initialization_tolerance_steps: 2000    # Tighter tolerance for initialization moves
  safety_margin_steps: 20000              # Safety margin from encoder limits
  max_position_error_steps: 15000         # Maximum position error before alert

# Monitoring settings
monitoring:
  status_update_interval: 1.0             # Status update frequency in seconds
  position_update_max_age: 5.0            # Maximum age of position data