calibrated: true
calibration_date: '2025-07-26T19:57:44.745975'
observer_latitude: -23.27
dec_limits:
  dec_angular_range: 235.0
  negative_degrees: -113.0
  positive_degrees: 122.0
limits:
  dec_negative: -500000
  dec_positive: 500000
  ra_negative: -1000000
  ra_positive: 1000000
limits_safety_factor: 0.1
ra_limits:
  negative_hours: 6
  positive_hours: -6
  ra_angular_range: 12.0
ranges:
  dec_encoder_range: 1000000
  ra_encoder_range: 2000000
sidereal_rate: -100
slew_speed: 5000
