# ROTSE-III Telescope Configuration for pyobs
# Example configuration file for the ROTSE3Telescope module with embedded telescope config

module: pyobs.modules.telescope.ROTSE3Telescope

# Slewing parameters
slew_timeout: 300.0                               # Maximum slew time (seconds)
position_tolerance: 0.01                          # Position tolerance (degrees)

# Site configuration (required for coordinate conversions)
timezone: -7                                      # Timezone offset from UTC
location:
  longitude: -111.6                               # HESS site longitude (degrees E)
  latitude: -23.27                                # HESS site latitude (degrees N)
  elevation: 1800                                 # Site elevation (meters)

# Safety limits
min_altitude: 10.0                                # Minimum altitude (degrees)

# FITS headers (optional)
fits_headers:
  TELESCOP: ["ROTSE-III", "Telescope name"]
  INSTRUME: ["ROTSE3-HESS", "Instrument name"] 
  SITE: ["HESS", "Observatory site"]
  OBSERVER: ["ROTSE-III", "Observer name"]

# Embedded telescope driver configuration
telescope:
  # Serial communication settings
  serial:
    port: "/dev/ttyS0"                            # Serial port device
    baudrate: 9600                                # Communication speed
    timeout: 2.0                                  # Command timeout (seconds)
    
  # Encoder limits and ranges
  limits:
    ha_positive: 262143                           # HA positive limit (18-bit encoder)
    ha_negative: -262144                          # HA negative limit
    dec_positive: 131071                          # Dec positive limit (17-bit encoder)
    dec_negative: -131072                         # Dec negative limit
    
  ranges:
    ha_encoder_range: 24.0                        # HA range in hours (±12h)
    dec_encoder_range: 180.0                      # Dec range in degrees (±90°)
    
  # Coordinate system and site parameters
  coordinates:
    longitude: -111.6                             # Site longitude (degrees E)
    latitude: -23.27                              # Site latitude (degrees N)
    elevation: 1800.0                             # Site elevation (meters)
    timezone: -7                                  # Timezone offset from UTC
    
  # Motion parameters for different slew modes
  motion:
    normal_speed: 600                             # Normal slew speed (steps/sec)
    precise_speed: 100                            # Precise slew speed (steps/sec)
    fast_speed: 1200                              # Fast slew speed (steps/sec)
    
  # Tracking parameters
  tracking:
    sidereal_rate: 15.041                         # Sidereal rate (arcsec/sec)
    update_interval: 1.0                          # Tracking update interval (seconds)
    
  # Safety parameters and limits
  safety:
    max_slew_time: 300.0                          # Maximum slew time (seconds)
    position_tolerance: 0.01                      # Position tolerance (degrees)
    min_altitude: 10.0                            # Minimum altitude (degrees)
    
  # Status monitoring settings
  monitoring:
    status_interval: 2.0                          # Status update interval (seconds)
    encoder_tolerance: 10                         # Encoder position tolerance (steps)

# Pyobs communication (optional)
comm:
  class: pyobs.comm.dummy.DummyComm              # Communication class

# Background tasks
background_tasks:
  - class: pyobs.background.PingTask
    interval: 60                                  # Ping interval (seconds)